export const DESTINATIONS = {
    MOON:   'MOON',
    MARS:   'MARS',
    EUROPA: 'EUROPA',
    TITAN:  'TITAN'
}

export const CREW = {
    COMMANDER: 'COMMANDER',
    MISSION_SPECIALIST: 'MISSION SPECIALIST',
    PILOT:  'PILOT',
    FLIGHT_ENGINEER: 'FLIGHT ENGINEER'
}

export const TECHNOLOGY = {
    LUNCH_VEHICLE:  'LUNCH VEHICLE',
    SPACEPORT:  'SPACEPORT',
    SPACE_CAPSULE:  'SPACE CAPSULE'
}